### ISSUE TITLE
Did the BundleID change?

### ISSUE THREAD

**Issue by waynebeaton** [eclipse/orbit#56]
The Eclipse Dash License Tool uses this repository to figure out how to map a bundle Id (e.g.,  `com.atlassian.commonmark-gfm-tables`) to the corresponding GAV (e.g., `com.atlassian.commonmark:commonmark-ext-gfm-tables`). The scanner walks this repository and pulls this information out of the `pom.xml` files. It generally works (with some small amount of hinting).

The expectation is that as we encounter new versions of things, they are likely to have similar IDs to the older versions. The exceptions are handled with the aforementioned small amount of hinting.

The Orbit build (the only information that I have is that the issue "was created 2 days ago by orbit bot user) recently created a handful of reviews for which the scanner cannot find source code. 

For example: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10695 (there's actually a bunch of similar "commonmark" entries).

Here... we need to map the bundle ID `org.commonmark-gfm-tables`. The closest that I can find in this repository is a bundle named `com.atlassian.commonmark-gfm-tables`. 

Are these the same thing? Did the name change intentionally? Is this a mistake?

**Comment by merks** [comment]
I think this ip lab issue was asking an analogous question so the same information applies:

https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10729

The dash scanner does significantly more than look at pom.xml files.  It also appears to monitor Tycho's processing of *.target files including Tycho's processing of the BND instructions used to wrap a Maven non-OSGi artifact as an OSGi bundle.

I see this in the log for the processing of the Maven GAV  `org.commonmark:commonmark-ext-gfm-tables:0.21.0`:
```
[INFO] org.commonmark:commonmark-ext-gfm-tables:0.21.0 is wrapped as a bundle with bundle symbolic name org.commonmark-gfm-tables
[INFO] The artifact can be referenced in feature files with the following data: <plugin id="org.commonmark-gfm-tables" version="0.21.0.v20230927-1332" download-size="0" install-size="0" unpack="false"/>
...
[INFO] A review request already exists https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/10732 .
[INFO] A review is required for p2/orbit/p2.eclipse.plugin/org.commonmark-gfm-tables/0.21.0.v20230927-1332.
```

This naming/version pattern is used because that was what was used in the past by Orbit EBR-baed builds which presumably haven been IP reviewed in the past:

- https://download.eclipse.org/tools/orbit/downloads/drops/N20230908195041/repository/plugins/com.atlassian.commonmark-gfm-tables_0.15.1.v20221112-0806.jar
- https://github.com/eclipse-orbit/orbit/blob/main/commonmark/com.atlassian.commonmark-gfm-tables_0.15.1/osgi.bnd

So yes, the latter is derived from the former, and the naming is often driven by what was done previous by the Orbit EBR builds so that the resulting bundles retain the same symbolic name as was historically the case.
